### ISSUE TITLE
timestamp migrations do not work in MariaDB

### ISSUE THREAD

**Issue by cebe** [cebe/yii2-openapi#100]
```yaml
   Customer:
      description: customer is the one that orders a campaign
      type: object
      required:
        - id
        - name
        - created_at

      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 100

        created_at:
          type: string
          format: datetime
          nullable: false
          x-db-type: datetime
          default: CURRENT_TIMESTAMP
        updated_at:
          type: string
          format: datetime
          default: null
          nullable: true
          x-db-type: datetime
```

generates a migration:

```php
class m220524_140002_change_table_customers extends \yii\db\Migration
{
    public function up()
    {
        $this->alterColumn('{{%customers}}', 'created_at', $this->timestamp()->notNull()->defaultExpression("CURRENT_TIMESTAMP"));
    }

    public function down()
    {
        $this->alterColumn('{{%customers}}', 'created_at', $this->timestamp()->notNull()->defaultExpression("CURRENT_TIMESTAMP"));
    }
}
```

**Comment by cebe** [comment]
similar behavior for ENUM colums, existing column gets an update which removes the "string type":

```yaml
      properties:
        system:
          type: string
          maxLength: 10
          enum:
            - mail
            - test
            - other
```

generates:

```php
class m220524_140005_change_table_mailings extends \yii\db\Migration
{
    public function up()
    {
        $this->alterColumn('{{%mailings}}', 'system', $this->notNull());
    }

    public function down()
    {
        $this->alterColumn('{{%mailings}}', 'system', $this->string(10)->notNull());
    }
}
```
