### ISSUE TITLE
Migration Generator: Default value for integer should not be considered string

### ISSUE THREAD

**Issue by cebe** [cebe/yii2-openapi#11]
Having the following OpenAPI schema:

```yaml
  flags:
    type: integer
    default: 0
```

and a column in the database: `flags INT DEFAULT 0`

The following migration is generated:

```php
/**
 * Table for User
 */
class m200803_210000_change_table_users extends \yii\db\Migration
{
    public function safeUp()
    {
        $this->alterColumn('{{%users}}', 'flags', "SET DEFAULT 0");
    }

    public function safeDown()
    {
        $this->alterColumn('{{%users}}', 'flags', "SET DEFAULT '0'");
    }
}
```

Changing yaml to:

```yaml
  flags:
    type: integer
    default: "0"
```

making the 0 a string value does not generate a migration.

This happens on Postgres.
