### ISSUE TITLE
For ENUM colums, existing column gets an update which removes the "string type"

### ISSUE THREAD

**Issue by SOHELAHMED7** [cebe/yii2-openapi#111]
https://github.com/cebe/yii2-openapi/issues/100#issuecomment-1135982903

TODO

 - [x] add back status column as enum in tests/specs/postgres_custom.yaml (see https://github.com/cebe/yii2-openapi/pull/112/files - Ctrl+F: `vector`)
 - [x] add back `status` 'gin(to_tsvector(\'english\', status))' in index in tests/specs/postgres_custom.yaml.
 - [x] ~add tests for x-db-type (for enum): fresh, secondary with new col; secondary with edit col:~ Note needed 
 - [x] https://dev.mysql.com/doc/refman/8.0/en/enum.html

**Comment by cebe** [comment]
this should already be fixed by #103

**Comment by SOHELAHMED7** [comment]
Enum behaviour will likely to be changed:

Currently we provide `x-db-type` for `enum` fields/columns.

Enum is not a real data type in Pgsql

Ideally we provide `x-db-type` when we have more than one way to store same data. E.g. time: we can store it as timestamp or datetime string.

For enum no matter what database we use, we store it as corresponding enum way. There is no more than one way to store enum values in DB.

Changes I will implement for enum if there is a enum field in yml:

 -  if we provide `x-db-type` an error will be thrown that setting `x-db-type` has no effect and should be avoided. For enum fields yii2-openapi lib will automatically create enum column/type depending on the DB type


Incorrect:

```
lang:
          type: string
          x-db-type: enum
          enum:
            - ru
            - eng
```

Correct:

```
lang:
          type: string
          enum:
            - ru
            - eng
```

@cebe please comment if there is anything wrong with above approach.
