### ISSUE TITLE
Generated REST URL rules should allow dot in URL

### ISSUE THREAD

**Issue by SOHELAHMED7** [cebe/yii2-openapi#113]
Lets say I have path `/mail/domain/{name}` in OpenAPI.

REST URL rules generated for it will be 

`GET mail/domain/<name:[\w-]+>`

Above rule will not function for URL `http://example.com/mail/domain/github.com`

because `github.com` have dot (`.`)

Regex to include dot (`.`) will be `mail/domain/<name:[\w.-]+>`. So API generator should generate this URL rule to consider dot.

**Comment by cebe** [comment]
Regex should be customizable

**Comment by SOHELAHMED7** [comment]
Regex should be customizable at which level?

At lib config in PHP:

```php
$generator = new ApiGenerator([
    ...
    'regex' => '[\w-]', <--- new config
    ...
]);
```

or for every path in OpenAPI:

```yaml
# OpenAPI spec

paths:

  '/company/{companyId}/bank-accounts':
    parameters:
      - name: companyId
        in: path
        description: ID of the company.
        x-regex: '[\w-]'     <--- new config
        required: true
        schema:
          type: integer



```

**Comment by cebe** [comment]
> Regex should be customizable at which level?

for path in OpenAPI, we can check the pattern on the schema:

```yaml
# OpenAPI spec

paths:

  '/domains/{domainname}':
    parameters:
      - name: domainname
        in: path
        description: dns domain name
        required: true
        schema:
          type: string
          pattern: '^[a-z-]$'

```

https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-6.3.3
https://json-schema.org/understanding-json-schema/reference/regular_expressions.html

Note that `^` and `$` should be removed when the value is inserted into  yii routing rules.
