### ISSUE TITLE
Errors in migrations in case of editing a field name for MySQL

### ISSUE THREAD

**Issue by SOHELAHMED7** [cebe/yii2-openapi#114]
I have a field in OpenAPI schema:

```
updated_at:
          readOnly: true
          type: string
          format: datetime
          nullable: false
          x-db-type: datetime
```

If I change its name to `updated_at2` then run `$ ./yii gii/api` I get following migrations generated for MySQL

```php
class m221004_140000_change_table_pets extends \yii\db\Migration
{
    public function up()
    {
        $this->addColumn('{{%pets}}', 'updated_at2', $this->timestamp()->notNull());
        $this->dropColumn('{{%pets}}', 'updated_at');
        $this->alterColumn('{{%pets}}', 'created_at', $this->timestamp()->notNull());
    }

    public function down()
    {
        $this->alterColumn('{{%pets}}', 'created_at', $this->datetime()->notNull());
        $this->addColumn('{{%pets}}', 'updated_at', $this->datetime()->notNull());
        $this->dropColumn('{{%pets}}', 'updated_at2');
    }
}

```

Issues:

1. migration for `created_at` which is above `updated_at` should not be generated as it is not changed
2. `datetime()` should be used instead of `timestamp()` (issue logged at https://github.com/cebe/yii2-openapi/issues/100)
3. `down()` code is erroneous
