### ISSUE TITLE
Implement default by literal expression using new field 'x-db-default-expression'

### ISSUE THREAD

**Issue by SOHELAHMED7** [cebe/yii2-openapi#121]
Default in DB can be by literal constant or an expression.

Examples: https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html

```sql
CREATE TABLE t1 (
  -- literal defaults
  i INT         DEFAULT 0,
  c VARCHAR(10) DEFAULT '',
  -- expression defaults
  f FLOAT       DEFAULT (RAND() * RAND()),
  b BINARY(16)  DEFAULT (UUID_TO_BIN(UUID())),
  d DATE        DEFAULT (CURRENT_DATE + INTERVAL 1 YEAR),
  p POINT       DEFAULT (Point(0,0)),
  j JSON        DEFAULT (JSON_ARRAY())
);
```

OpenAPI `default` is used for literal constant

Implement new key `x-db-default-expression` for allowing default value by literal expression

Example:

```yaml
created_at:
          readOnly: true
          type: string
          format: datetime
          x-db-type: datetime
          nullable: false
          x-db-default-expression: current_timestamp()
```
