### ISSUE TITLE
In Pgsql, column data type change from varchar(255) to json "using" should be used

### ISSUE THREAD

**Issue by SOHELAHMED7** [cebe/yii2-openapi#125]
In Pgsql, if we change db type from varchar(255) to json, alter column statement should have "using".

Example:

From:

```yaml
name:
          type: string
          x-db-type: varchar(255)
```

To:

```yaml
name:
          type: array
          x-db-type: JSON
          nullable: false
          default: '{}'
```

This should not be generated in migration:

```php
$this->db->createCommand('ALTER TABLE {{%fruits}} ALTER COLUMN name SET DATA TYPE json')->execute();
```

But this should be generated:

```php
$this->db->createCommand('ALTER TABLE {{%fruits}} ALTER COLUMN name SET DATA TYPE json using "name"::json')->execute();
```

---

PR will be https://github.com/SOHELAHMED7/yii2-openapi/pull/7
