### ISSUE TITLE
Migration Generator: Default value for JSON column generates a migration for equal values

### ISSUE THREAD

**Issue by cebe** [cebe/yii2-openapi#13]
Schema in OpenAPI:

```yaml
  customFields:
    type: array
    x-db-type: json
    default: '[]'
    items:
      type: object
```

generated migration:

```php
class m200803_210001_change_table_projects extends \yii\db\Migration
{
    public function safeUp()
    {
        $this->alterColumn('{{%projects}}', 'customFields', "SET DEFAULT '[]'");
    }

    public function safeDown()
    {
        $this->alterColumn('{{%projects}}', 'customFields', "SET DEFAULT '[]'");
    }
}
```

There is no change in up and down.

This happens on PostgreSQL

**Comment by Insolita** [comment]
Is it the bug because for downCode should be  another default value, or this migration should be skipped because default values are same?

**Comment by Insolita** [comment]
Catch it. I assumes that default value for json/array fields will be set without quotes 
```
  customFields:
    type: array
    x-db-type: json
    default: []
    items:
      type: object
```

```
  customFields:
    type: array
    x-db-type: json
    default: 
         - key1: value1
         - key2: value2
```
