### ISSUE TITLE
If data type is not changed then still migrations are generated for timestamp in MySQL

### ISSUE THREAD

**Issue by SOHELAHMED7** [cebe/yii2-openapi#143]
**DB**: MySQL

**OpenAPI schema**:

```yaml
# User:
title: User
x-table: user
type: object
description: Database schema of a User.

# ...

properties:

  id:
    type: integer
    readOnly: true
    example: 1337


  # other fields...

  created_at:
    type: string
    format: date-time
    example: '2020-03-14T21:42:17Z'
    readOnly: true

  updated_at:
    type: string
    format: date-time
    example: '2020-03-14T21:42:17Z'
    readOnly: true



```

**Generated migrations** :

![unwanted-migrations](https://user-images.githubusercontent.com/6770119/230839240-da2c0ae9-1a29-4366-8122-31b0407cdf96.png)

**Expected**: 

This migrations does not make any sense and should not be generated

**Hint for solution**: This happens because we haven't explicitly mentioned `x-db-type`, so by default it is considered timestamp data type

**Type**: Bug
