### ISSUE TITLE
Consider default constant values in model validation rules

### ISSUE THREAD

**Issue by SOHELAHMED7** [cebe/yii2-openapi#154]
```yaml
        billing_factor:
          description: integer between 0 and 100, default value 100
          type: integer
          default: 100
          nullable: false
          x-faker: '$faker->numberBetween(0, 100)'

```

in model validation rules, it should be in `default` validation rule
