### ISSUE TITLE
Alter column forgets about NOT NULL constraint

### ISSUE THREAD

**Issue by cebe** [cebe/yii2-openapi#37]
I just noticed where the NOT NULL migrations come from, which were broken today.

```yaml
# Lead:
title: Lead
x-table: leads
type: object
description: Database schema of a Lead.

required:
 - id
 - createdAt

properties:

  id:
    type: integer
    example: 12531
    readOnly: true

  createdAt:
    type: string
    format: date
    example: '2020-03-14T21:42:17Z'
    readOnly: True
```

I changed a format of `createdAt` to `date-time`, the generated migration was:

```php
        $this->alterColumn('{{%leads}}', 'createdAt', $this->timestamp());
```

but should have been:

```php
        $this->alterColumn('{{%leads}}', 'createdAt', $this->timestamp()->notNull());
```
