### ISSUE TITLE
Bool field with default value and not in required section generate null() in migration files

### ISSUE THREAD

**Issue by SOHELAHMED7** [cebe/yii2-openapi#63]
For field with bool data type which have default value either `true` or `false`, and not in required section,

its migration is generated as

`$this->boolean()->null()->defaultValue(false)`

Ideally it should be 

`$this->boolean()->defaultValue(false)` (or `true` as default value) no matter it is in required section or nor

Feel free to let me know if more info is needed.

**Comment by Insolita** [comment]
What is wrong? We generate all properties explicitly, even they are default.

**Comment by SOHELAHMED7** [comment]
If a property is of type `boolean` and has default value then this should not be generated in  migration file:

```php
$this->boolean()->null()->defaultValue(false)
```

Here `null()` is present however ideally it should be there.

In correct scenario IMHO it should be 

`$this->boolean()->defaultValue(false)`

**Comment by Insolita** [comment]
But boolean fields may be stored with allowing null as well as without, it depends on a case. Some of them may require indeterminate state

**Comment by Insolita** [comment]
Null/Not null state depends on the "requirement" property in your model schema definition. 

````
title: MyTable
x-table: my_table
type:object
required:
   - id
   - name
   - is_active

properties:
    id:
        type: integer
        readOnly: true
   name: 
       type: string
   is_active:
       type: boolean
       default: false
   is_confirmed:
       type: boolean
       default: false
````

will generate 
for is_active
`$this->boolean()->notNull()->defaultValue(false) `
and for is_confirmed
`$this->boolean()->null()->defaultValue(false) `
