### ISSUE TITLE
Allow  NULL in x-db-type jsonb 

### ISSUE THREAD

**Issue by SOHELAHMED7** [cebe/yii2-openapi#89]
At the moment if I create a property named (for e.g.) `res_header`  with required `false` and x-db-type `jsonb`, migrations generated have `'response_headers' => 'jsonb NOT NULL',`

Example: Del.yaml

```yaml
# del:
title: Del
x-table: del
type: object


required:
  - id 

  # ...
  
  # - res_header #not required
  

  # ...
  

properties:

  id:
    type: integer
    readOnly: true
    example: 1337

  res_header:
    type: array
    x-db-type: jsonb
    example:
      - {"atl-traceid": "16eae2fc924", "content-encoding": "gzip", "content-type": "text/html", "date": "Thu, 02 Dec 2021 12:59:38 GMT", "referrer-policy": "strict-origin-when-cross-origin"}
    description: Response header 
    items:
      type: object  

    # ...
      
```

Expected:

Yii2 migration should have allow null

e.g. `'response_headers' => 'jsonb',`
