### ISSUE TITLE
Prevent _id suffix in column name on reference properties 

### ISSUE THREAD

**Issue by SOHELAHMED7** [cebe/yii2-openapi#90]
I have Open API model that represents a DB table

```yaml
# del:
title: Del
x-table: del
type: object


required:
  - id 
  - user

  # ...

properties:

  id:
    type: integer
    readOnly: true
    example: 1337

  user:
    $ref: '../openapi.yaml#/components/schemas/User' # this will automatically create `user_id` columns

    # ...

```

here `_id` is automatically get suffixed to `user`. That is helpful in lot of cases.

However in certain cases, I would like to have column name that is a reference but not suffixed by `_id` and having custom column name

Example:

```yaml
# del:
title: Del
x-table: del
type: object


required:
  - id 

  # ...

properties:

  id:
    type: integer
    readOnly: true
    example: 1337

  redelivery_of:
    $ref: '../openapi.yaml#/components/schemas/Del' 

    # ...

```

this `redelivery_of` reference to PK of same table and custom column name needed here is `redelivery_of` instead of `redelivery_of_id`

Meta:

 - feature request
